name: nrnerf
channels:
  - conda-forge
  - pytorch
dependencies:
 - python=3.7.*
 - anaconda::configargparse
 - pytorch=1.6.0
 - torchvision=0.7.0
 - imageio
 - imageio-ffmpeg
 - matplotlib
 - tqdm
 - opencv=4.4.0
